Fix for crash on launch if interactables try to register themselves too soon
Our user testing has found the following periodic crash on launch:

```
[NewtonVR] Error: NVRInteractables.Register called before initialization.
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

NullReferenceException: Object reference not set to an instance of an object
  at NewtonVR.NVRInteractables.Register (NewtonVR.NVRInteractable interactable, UnityEngine.Collider[] colliders) [0x00000] in <filename unknown>:0 
  at NewtonVR.NVRInteractable.UpdateColliders () [0x00000] in <filename unknown>:0 
  at NewtonVR.NVRInteractableItem.UpdateColliders () [0x00000] in <filename unknown>:0 
  at NewtonVR.NVRInteractable.Start () [0x00000] in <filename unknown>:0 
  at NewtonVR.NVRInteractableItem.Start () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

NullReferenceException: Object reference not set to an instance of an object
  at Flipside.Loader.SetAppMode (AppMode newMode) [0x00000] in <filename unknown>:0 
  at Flipside.Loader+<Initialize>c__Iterator36.MoveNext () [0x00000] in <filename unknown>:0 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)
```